# docker-compose.yml
version: '3.8'

services:
  back-produtividade:
    build: .
    ports:
      - "4000:4000"
    # As variáveis de ambiente serão agora injetadas pelo Portainer.
    # Removida a diretiva 'env_file'.
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      # Adicione outras variáveis que precisar aqui, seguindo o mesmo formato.
      # Ex: - PORT=${PORT}
