version: '3.8'

services:
  backend:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT:-4000}
    ports:
      - "4000:4000"  # Expõe a porta 4000 do container na porta 5000 do host
    networks:
      - proxy
    labels:
      # --- Habilita o Traefik para este serviço ---
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${PRODUTIVIDADE_HOST}`)"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"

networks:
  proxy:
    external: true
